#!/bin/bash
./process-raw-data.sh busybox 1 10
./process-raw-data.sh telegraf 1 10
./process-raw-data.sh consul 1 50
./process-raw-data.sh sourcemage 1 10
./process-raw-data.sh crate 1 10
./process-raw-data.sh kong 1 10
./process-raw-data.sh mediawiki 1 10
./process-raw-data.sh euleros 1 10
./process-raw-data.sh piwik 1 10
./process-raw-data.sh alt 1 10
./process-raw-data.sh ros 1 10
./process-raw-data.sh buildpack-deps 1 10
./process-raw-data.sh hello-world 1 10
./process-raw-data.sh geonetwork 1 10
./process-raw-data.sh nats 1 10
./process-raw-data.sh sonarqube 1 10
./process-raw-data.sh celery 1 10
./process-raw-data.sh neurodebian 1 10
./process-raw-data.sh glassfish 1 10
./process-raw-data.sh xwiki 1 10
./process-raw-data.sh erlang 1 10
./process-raw-data.sh cirros 1 10
./process-raw-data.sh teamspeak 1 10
./process-raw-data.sh flink 1 10
./process-raw-data.sh opensuse 1 10
./process-raw-data.sh express-gateway 1 10
./process-raw-data.sh pypy 1 10
./process-raw-data.sh alpine 1 10
./process-raw-data.sh couchbase 1 10
./process-raw-data.sh gazebo 1 10
./process-raw-data.sh rabbitmq 1 10
./process-raw-data.sh gradle 1 10
./process-raw-data.sh orientdb 1 10
./process-raw-data.sh eggdrop 1 10
./process-raw-data.sh chronograf 1 10
./process-raw-data.sh fsharp 1 10
./process-raw-data.sh centos 1 10
./process-raw-data.sh hipache 1 10
./process-raw-data.sh zookeeper 1 10
./process-raw-data.sh kibana 1 10
./process-raw-data.sh znc 1 10
./process-raw-data.sh rapidoid 1 10
./process-raw-data.sh open-liberty 1 10
./process-raw-data.sh amazoncorretto 1 10
./process-raw-data.sh mongo-express 1 10
./process-raw-data.sh lightstreamer 1 10
./process-raw-data.sh rocket.chat 1 10
./process-raw-data.sh clearlinux 1 10
./process-raw-data.sh kapacitor 1 10
./process-raw-data.sh influxdb 1 10
./process-raw-data.sh maven 1 10
./process-raw-data.sh odoo 1 10
./process-raw-data.sh notary 1 10
./process-raw-data.sh swift 1 10
./process-raw-data.sh logstash 1 10
./process-raw-data.sh bash 1 10
./process-raw-data.sh thrift 1 10
./process-raw-data.sh haproxy 1 10
./process-raw-data.sh drupal 1 10
./process-raw-data.sh mono 1 10
./process-raw-data.sh joomla 1 10
./process-raw-data.sh adminer 1 10
./process-raw-data.sh ubuntu-debootstrap 1 10
./process-raw-data.sh convertigo 1 10
./process-raw-data.sh clojure 1 10
./process-raw-data.sh amazonlinux 1 10
./process-raw-data.sh rakudo-star 1 10
./process-raw-data.sh yourls 1 10
./process-raw-data.sh spiped 1 10
./process-raw-data.sh elixir 1 10
./process-raw-data.sh irssi 1 10
./process-raw-data.sh julia 1 10
./process-raw-data.sh jruby 1 10
./process-raw-data.sh haskell 1 10
./process-raw-data.sh composer 1 10
./process-raw-data.sh neo4j 1 10
./process-raw-data.sh plone 1 10
./process-raw-data.sh eclipse-mosquitto 1 10
./process-raw-data.sh swipl 1 10
./process-raw-data.sh java 1 10
./process-raw-data.sh bonita 1 10
./process-raw-data.sh solr 1 10
./process-raw-data.sh jetty 1 10
./process-raw-data.sh rails 1 10
./process-raw-data.sh perl 1 10
./process-raw-data.sh swarm 1 10
./process-raw-data.sh redmine 1 10
./process-raw-data.sh wordpress 1 10
./process-raw-data.sh storm 1 10
./process-raw-data.sh haxe 1 10
./process-raw-data.sh ubuntu-upstart 1 10
./process-raw-data.sh tomee 1 10
./process-raw-data.sh photon 1 10
./process-raw-data.sh r-base 1 10
./process-raw-data.sh known 1 10
./process-raw-data.sh nextcloud 1 10
./process-raw-data.sh groovy 1 10
./process-raw-data.sh iojs 1 10
./process-raw-data.sh ibmjava 1 10
./process-raw-data.sh rethinkdb 1 10
./process-raw-data.sh hello-seattle 1 10
./process-raw-data.sh golang 1 10
./process-raw-data.sh mageia 1 10
./process-raw-data.sh owncloud 1 10
./process-raw-data.sh websphere-liberty 1 10
./process-raw-data.sh cassandra 1 10
./process-raw-data.sh gcc 1 10
./process-raw-data.sh hola-mundo 1 10
./process-raw-data.sh fedora 1 10
./process-raw-data.sh matomo 1 10
./process-raw-data.sh couchdb 1 10
./process-raw-data.sh arangodb 1 10
./process-raw-data.sh postfixadmin 1 10
./process-raw-data.sh jenkins 1 10
./process-raw-data.sh hylang 1 10
./process-raw-data.sh percona 1 10
./process-raw-data.sh registry 1 100
./process-raw-data.sh mariadb 1 10
./process-raw-data.sh debian 1 10
./process-raw-data.sh ghost 1 10
./process-raw-data.sh php-zendserver 1 10
./process-raw-data.sh tomcat 1 10
./process-raw-data.sh nats-streaming 1 10
./process-raw-data.sh django 1 10
./process-raw-data.sh sl 1 10
./process-raw-data.sh docker 1 10
./process-raw-data.sh backdrop 1 10
